<a href="https://colab.research.google.com/github/o1iviachen/pytorch-practice/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [22]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [23]:
# Import torch
import torch

# Create random tensor
t1 = torch.rand(7,7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [24]:
# Create another random tensor
t2 = torch.rand(1,7)
# Perform matrix multiplication
t1 @ t2.T

tensor([[0.5980],
        [1.7239],
        [2.1296],
        [1.8805],
        [2.0485],
        [1.5951],
        [2.1393]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [32]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
t3 = torch.rand(2,2)
torch.manual_seed(RANDOM_SEED)
t4 = torch.rand(2,2)

# Matrix multiply tensors
tmm1 = t3 @ t4
tmm1, tmm1.size()

(tensor([[0.3142, 0.4827],
         [0.0556, 0.0854]]),
 torch.Size([2, 2]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [33]:
# Set random seed


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tg1 = torch.rand(2, 3).to(device)
tg2 = torch.rand(2, 3).to(device)
tg1, tg2

Device: cuda


(tensor([[0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323]], device='cuda:0'),
 tensor([[0.3489, 0.4017, 0.0223],
         [0.1689, 0.2939, 0.5185]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [34]:
# Perform matmul on tensor_A and tensor_B
tmm2 = tg1 @ tg2.T
tmm2, tmm2.size()

(tensor([[0.3729, 0.4924],
         [0.5099, 0.6131]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
tmm2.max()
# Find min
tmm2.min()

tensor(0.3729, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
tmm2.argmax()
# Find arg min
tmm2.argmin()


tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [36]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
t5 = torch.rand(1, 1, 1, 10)
print(t5, t5.shape)

# Remove single dimensions
t6 = t5.squeeze()

# Print out tensors and their shapes
t6, t6.shape

tensor([[[[0.9527, 0.0362, 0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698,
           0.1507, 0.0317]]]]) torch.Size([1, 1, 1, 10])


(tensor([0.9527, 0.0362, 0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507,
         0.0317]),
 torch.Size([10]))